#include "src/game/envfx_snow.h"

const GeoLayout heather_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 63, 0, heather_head_mesh_mat_override_sm64_material_004_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_ear_left_skinned_mat_override_sm64_material_004_0),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -26, 102, -5, -5, -2, 13),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, heather_ear_left_mesh_mat_override_sm64_material_004_0),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_ear_left_end_skinned_mat_override_sm64_material_004_0),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 35, 0, 8, -4, 24),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, heather_ear_left_end_mesh_mat_override_sm64_material_004_0),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_ear_right_skinned_mat_override_sm64_material_004_0),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 24, 102, -5, -1, 0, -15),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, heather_ear_right_mesh_mat_override_sm64_material_004_0),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_ear_right_end_skinned_mat_override_sm64_material_004_0),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 34, 0, 0, -6, -16),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, heather_ear_right_end_mesh_mat_override_sm64_material_004_0),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_hairend_skinned_mat_override_sm64_material_004_0),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -18, 31, heather_hairend_mesh_mat_override_sm64_material_004_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout heather_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 63, 0, heather_head_mesh_mat_override_sm64_material_016_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_ear_left_skinned_mat_override_sm64_material_016_1),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -26, 102, -5, -5, -2, 13),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, heather_ear_left_mesh_mat_override_sm64_material_016_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_ear_left_end_skinned_mat_override_sm64_material_016_1),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 35, 0, 8, -4, 24),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, heather_ear_left_end_mesh_mat_override_sm64_material_016_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_ear_right_skinned_mat_override_sm64_material_016_1),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 24, 102, -5, -1, 0, -15),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, heather_ear_right_mesh_mat_override_sm64_material_016_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_ear_right_end_skinned_mat_override_sm64_material_016_1),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 34, 0, 0, -6, -16),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, heather_ear_right_end_mesh_mat_override_sm64_material_016_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_hairend_skinned_mat_override_sm64_material_016_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -18, 31, heather_hairend_mesh_mat_override_sm64_material_016_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout heather_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, heather_body_mesh),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_arm_left_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -27, 46, -2, 36, 6, 99),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, heather_arm_left_mesh),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_arm_left_middle_skinned),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 20, 0, 6, 1, -5),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, heather_arm_left_middle_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_arm_left_end_skinned),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 12, 0, -14, -1, -8),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, heather_arm_left_end_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_arm_right_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 27, 45, 2, -35, 6, -100),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, heather_arm_right_mesh),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_arm_right_middle_skinned),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 19, 0, -6, 0, 5),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, heather_arm_right_middle_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_arm_right_end_skinned),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 12, 0, 14, -1, 8),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, heather_arm_right_end_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_foot_left_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -24, -22, -2, 7, 35, 169),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, heather_foot_left_mesh),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_foot_right_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 24, -22, 2, -7, 35, -169),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, heather_foot_right_mesh),
			GEO_CLOSE_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_heather_eyes),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 63, 0, heather_head_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_ear_left_skinned),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -26, 102, -5, -5, -2, 13),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, heather_ear_left_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_ear_left_end_skinned),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 35, 0, 8, -4, 24),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, heather_ear_left_end_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_ear_right_skinned),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 24, 102, -5, -1, 0, -15),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, heather_ear_right_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_ear_right_end_skinned),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 34, 0, 0, -6, -16),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, heather_ear_right_end_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_hairend_skinned),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -18, 31, heather_hairend_mesh),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, heather_switch_opt1),
				GEO_BRANCH(1, heather_switch_opt2),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, heather_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
