#include "src/game/envfx_snow.h"

const GeoLayout mike_Bone_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 63, 0, mike_head_mesh_mat_override_sm64_material_004_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, mike_ear_left_skinned_mat_override_sm64_material_004_0),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -26, 102, 0, 0, 0, 25),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mike_ear_left_mesh_mat_override_sm64_material_004_0),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, mike_ear_right_skinned_mat_override_sm64_material_004_0),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 24, 102, 1, 0, 0, -25),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mike_ear_right_mesh_mat_override_sm64_material_004_0),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 108, 1, NULL),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mike_Bone_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 63, 0, mike_head_mesh_mat_override_sm64_material_012_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, mike_ear_left_skinned_mat_override_sm64_material_012_1),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -26, 102, 0, 0, 0, 25),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mike_ear_left_mesh_mat_override_sm64_material_012_1),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, mike_ear_right_skinned_mat_override_sm64_material_012_1),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 24, 102, 1, 0, 0, -25),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mike_ear_right_mesh_mat_override_sm64_material_012_1),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 108, 1, NULL),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mike_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, -1, 117, 5, mike_body_mesh),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_jowee_eyes),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 63, 0, mike_head_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, mike_ear_left_skinned),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -26, 102, 0, 0, 0, 25),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mike_ear_left_mesh),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, mike_ear_right_skinned),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 24, 102, 1, 0, 0, -25),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mike_ear_right_mesh),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 108, 1, NULL),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, mike_Bone_opt1),
				GEO_BRANCH(1, mike_Bone_opt2),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, mike_arm_left_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -36, 41, -2, 33, 16, 117),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mike_arm_left_mesh),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, mike_arm_left_middle_skinned),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 21, 0, 5, -1, -4),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mike_arm_left_middle_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, mike_arm_left_end_skinned),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 13, 0, -12, 1, -7),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mike_arm_left_end_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, mike_arm_right_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 35, 41, 2, -33, 16, -117),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mike_arm_right_mesh),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, mike_arm_right_middle_skinned),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 21, 0, -5, -1, 4),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mike_arm_right_middle_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, mike_arm_right_end_skinned),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 13, 0, 12, 1, 7),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mike_arm_right_end_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, mike_foot_left_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -29, -22, -2, 9, 35, 167),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mike_foot_left_mesh),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, mike_foot_right_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 28, -22, 2, -9, 35, -167),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, mike_foot_right_mesh),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, mike_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
