#include "src/game/envfx_snow.h"

const GeoLayout baki_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 17, 0, baki_body_mesh),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, baki_left_leg_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -16, -4, 0, 0, -90, -180),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, baki_left_leg_mesh),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, baki_right_leg_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 16, -4, 0, 0, -90, -180),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, baki_right_leg_mesh),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 8, -9, baki_scarf_tilt_mesh),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, baki_scarf_skinned),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 10, 9, -36, -76, -75, 78),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, baki_scarf_mesh),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, baki_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
