extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern Vtx wf_dl_Plane_mesh_vtx_0[1307];
extern Gfx wf_dl_Plane_mesh_tri_0[];
extern Vtx wf_dl_Plane_mesh_vtx_1[382];
extern Gfx wf_dl_Plane_mesh_tri_1[];
extern Vtx wf_dl_Plane_mesh_vtx_2[1165];
extern Gfx wf_dl_Plane_mesh_tri_2[];
extern Vtx wf_dl_Plane_mesh_vtx_3[276];
extern Gfx wf_dl_Plane_mesh_tri_3[];
extern Vtx wf_dl_Plane_mesh_vtx_4[96];
extern Gfx wf_dl_Plane_mesh_tri_4[];
extern Vtx wf_dl_Plane_mesh_vtx_5[172];
extern Gfx wf_dl_Plane_mesh_tri_5[];
extern Vtx wf_dl_Plane_mesh_vtx_6[252];
extern Gfx wf_dl_Plane_mesh_tri_6[];
extern Vtx wf_dl_Plane_mesh_vtx_7[14];
extern Gfx wf_dl_Plane_mesh_tri_7[];
extern Vtx wf_dl_Plane_mesh_vtx_8[36];
extern Gfx wf_dl_Plane_mesh_tri_8[];
extern Vtx wf_dl_Plane_mesh_vtx_9[23];
extern Gfx wf_dl_Plane_mesh_tri_9[];
extern Vtx wf_dl_Plane_001_mesh_vtx_0[347];
extern Gfx wf_dl_Plane_001_mesh_tri_0[];

extern Gfx wf_dl_Plane_mesh[];
extern Gfx wf_dl_Plane_001_mesh[];
extern Gfx wf_dl_material_revert_render_settings[];

