extern const GeoLayout ttc_area_1_geo[];
extern const GeoLayout ttc_area_1[];
extern const Collision ttc_area_1_collision[];
extern const MacroObject ttc_area_1_macro_objs[];
extern Vtx ttc_dl_Cube_mesh_vtx_0[717];
extern Gfx ttc_dl_Cube_mesh_tri_0[];
extern Vtx ttc_dl_Cube_mesh_vtx_1[206];
extern Gfx ttc_dl_Cube_mesh_tri_1[];
extern Vtx ttc_dl_Cube_mesh_vtx_2[238];
extern Gfx ttc_dl_Cube_mesh_tri_2[];
extern Vtx ttc_dl_Cube_mesh_vtx_3[143];
extern Gfx ttc_dl_Cube_mesh_tri_3[];
extern Vtx ttc_dl_Cube_mesh_vtx_4[4];
extern Gfx ttc_dl_Cube_mesh_tri_4[];
extern Vtx ttc_dl_Cube_002_mesh_vtx_0[331];
extern Gfx ttc_dl_Cube_002_mesh_tri_0[];
extern Vtx ttc_dl_Cube_002_mesh_vtx_1[977];
extern Gfx ttc_dl_Cube_002_mesh_tri_1[];
extern Vtx ttc_dl_Cube_002_mesh_vtx_2[344];
extern Gfx ttc_dl_Cube_002_mesh_tri_2[];
extern Vtx ttc_dl_Cube_002_mesh_vtx_3[11];
extern Gfx ttc_dl_Cube_002_mesh_tri_3[];
extern Vtx ttc_dl_Cube_002_mesh_vtx_4[219];
extern Gfx ttc_dl_Cube_002_mesh_tri_4[];
extern Vtx ttc_dl_Cube_002_mesh_vtx_5[240];
extern Gfx ttc_dl_Cube_002_mesh_tri_5[];
extern Vtx ttc_dl_Cube_002_mesh_vtx_6[54];
extern Gfx ttc_dl_Cube_002_mesh_tri_6[];
extern Vtx ttc_dl_Cube_002_mesh_vtx_7[26];
extern Gfx ttc_dl_Cube_002_mesh_tri_7[];
extern Vtx ttc_dl_Plane_mesh_vtx_0[456];
extern Gfx ttc_dl_Plane_mesh_tri_0[];
extern Vtx ttc_dl_Plane_mesh_vtx_1[25];
extern Gfx ttc_dl_Plane_mesh_tri_1[];
extern Vtx ttc_dl_Plane_mesh_vtx_2[4];
extern Gfx ttc_dl_Plane_mesh_tri_2[];
extern Vtx ttc_dl_Plane_002_mesh_vtx_0[137];
extern Gfx ttc_dl_Plane_002_mesh_tri_0[];

extern Gfx ttc_dl_Cube_mesh[];
extern Gfx ttc_dl_Cube_002_mesh[];
extern Gfx ttc_dl_Plane_mesh[];
extern Gfx ttc_dl_Plane_002_mesh[];
extern Gfx ttc_dl_material_revert_render_settings[];

