#include "src/game/envfx_snow.h"

const GeoLayout jowee_Bone_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 63, 0, jowee_head_mesh_mat_override_sm64_material_004_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_ear_left_skinned_mat_override_sm64_material_004_0),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -26, 102, 0, 0, 0, 25),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_ear_left_mesh_mat_override_sm64_material_004_0),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_ear_left_end_skinned_mat_override_sm64_material_004_0),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 35, 0, 4, -5, 24),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_ear_left_end_mesh_mat_override_sm64_material_004_0),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_ear_right_skinned_mat_override_sm64_material_004_0),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 24, 102, 1, 0, 0, -25),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_ear_right_mesh_mat_override_sm64_material_004_0),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_ear_right_end_skinned_mat_override_sm64_material_004_0),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 35, 0, -4, -5, -24),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_ear_right_end_mesh_mat_override_sm64_material_004_0),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 108, 1, jowee_goggles_mesh_mat_override_sm64_material_004_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout jowee_Bone_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 63, 0, jowee_head_mesh_mat_override_sm64_material_012_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_ear_left_skinned_mat_override_sm64_material_012_1),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -26, 102, 0, 0, 0, 25),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_ear_left_mesh_mat_override_sm64_material_012_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_ear_left_end_skinned_mat_override_sm64_material_012_1),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 35, 0, 4, -5, 24),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_ear_left_end_mesh_mat_override_sm64_material_012_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_ear_right_skinned_mat_override_sm64_material_012_1),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 24, 102, 1, 0, 0, -25),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_ear_right_mesh_mat_override_sm64_material_012_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_ear_right_end_skinned_mat_override_sm64_material_012_1),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 35, 0, -4, -5, -24),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_ear_right_end_mesh_mat_override_sm64_material_012_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 108, 1, jowee_goggles_mesh_mat_override_sm64_material_012_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout jowee_geo[] = {
	GEO_CULLING_RADIUS(5000),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, -1, -67, 5, jowee_body_mesh),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_jowee_eyes),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 63, 0, jowee_head_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_ear_left_skinned),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -26, 102, 0, 0, 0, 25),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_ear_left_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_ear_left_end_skinned),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 35, 0, 4, -5, 24),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_ear_left_end_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_ear_right_skinned),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 24, 102, 1, 0, 0, -25),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_ear_right_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_ear_right_end_skinned),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 35, 0, -4, -5, -24),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_ear_right_end_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 108, 1, jowee_goggles_mesh),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, jowee_Bone_opt1),
				GEO_BRANCH(1, jowee_Bone_opt2),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_arm_left_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -36, 41, -2, 33, 16, 117),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_arm_left_mesh),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_arm_left_middle_skinned),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 21, 0, 5, -1, -4),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_arm_left_middle_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_arm_left_end_skinned),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 13, 0, -12, 1, -7),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_arm_left_end_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_arm_right_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 35, 41, 2, -33, 16, -117),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_arm_right_mesh),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_arm_right_middle_skinned),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 21, 0, -5, -1, 4),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_arm_right_middle_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_arm_right_end_skinned),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 13, 0, 12, 1, 7),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_arm_right_end_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_foot_left_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -29, -22, -2, 9, 35, 167),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_foot_left_mesh),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_foot_right_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 28, -22, 2, -9, 35, -167),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_foot_right_mesh),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_scarf_left_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -23, 59, -38, -83, -15, 39),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_scarf_left_mesh),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_scarf_left_middle_skinned),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 38, 0, -25, 1, 21),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_scarf_left_middle_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_scarf_left_end_skinned),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 37, 0, 0, 0, -52),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_scarf_left_end_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_scarf_right_skinned),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 22, 57, -32, -80, -17, -3),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_scarf_right_mesh),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_scarf_right_middle_skinned),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 26, 0, -11, 1, -24),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_scarf_right_middle_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_scarf_right_end_skinned),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 33, 0, -21, 0, -1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jowee_scarf_right_end_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, jowee_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
