extern const GeoLayout pss_area_1_geo[];
extern const GeoLayout pss_area_1[];
extern const Collision pss_area_1_collision[];
extern const MacroObject pss_area_1_macro_objs[];
extern Vtx pss_dl_Cube_mesh_vtx_0[222];
extern Gfx pss_dl_Cube_mesh_tri_0[];
extern Vtx pss_dl_Cube_mesh_vtx_1[120];
extern Gfx pss_dl_Cube_mesh_tri_1[];
extern Vtx pss_dl_Cube_mesh_vtx_2[52];
extern Gfx pss_dl_Cube_mesh_tri_2[];
extern Vtx pss_dl_Cube_001_mesh_vtx_0[176];
extern Gfx pss_dl_Cube_001_mesh_tri_0[];
extern Vtx pss_dl_Cube_002_mesh_vtx_0[176];
extern Gfx pss_dl_Cube_002_mesh_tri_0[];
extern Vtx pss_dl_Cube_003_mesh_vtx_0[176];
extern Gfx pss_dl_Cube_003_mesh_tri_0[];
extern Vtx pss_dl_Cube_004_mesh_vtx_0[176];
extern Gfx pss_dl_Cube_004_mesh_tri_0[];
extern Vtx pss_dl_Cube_005_mesh_vtx_0[176];
extern Gfx pss_dl_Cube_005_mesh_tri_0[];
extern Vtx pss_dl_Cube_006_mesh_vtx_0[176];
extern Gfx pss_dl_Cube_006_mesh_tri_0[];
extern Vtx pss_dl_Cube_007_mesh_vtx_0[176];
extern Gfx pss_dl_Cube_007_mesh_tri_0[];
extern Vtx pss_dl_Cube_008_mesh_vtx_0[506];
extern Gfx pss_dl_Cube_008_mesh_tri_0[];
extern Vtx pss_dl_Cube_008_mesh_vtx_1[966];
extern Gfx pss_dl_Cube_008_mesh_tri_1[];
extern Vtx pss_dl_Cube_008_mesh_vtx_2[56];
extern Gfx pss_dl_Cube_008_mesh_tri_2[];
extern Vtx pss_dl_Cube_008_mesh_vtx_3[23];
extern Gfx pss_dl_Cube_008_mesh_tri_3[];
extern Vtx pss_dl_Cube_025_mesh_vtx_0[176];
extern Gfx pss_dl_Cube_025_mesh_tri_0[];

extern Gfx pss_dl_Cube_mesh[];
extern Gfx pss_dl_Cube_001_mesh[];
extern Gfx pss_dl_Cube_002_mesh[];
extern Gfx pss_dl_Cube_003_mesh[];
extern Gfx pss_dl_Cube_004_mesh[];
extern Gfx pss_dl_Cube_005_mesh[];
extern Gfx pss_dl_Cube_006_mesh[];
extern Gfx pss_dl_Cube_007_mesh[];
extern Gfx pss_dl_Cube_008_mesh[];
extern Gfx pss_dl_Cube_025_mesh[];
extern Gfx pss_dl_material_revert_render_settings[];

