#include "src/game/envfx_snow.h"

const GeoLayout book_of_life_page_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 32, -27, 42, -50, -3, 20),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, book_of_life_page_link1_mesh),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, book_of_life_page_link2_skinned),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 16, 0, 1, -2, 17),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, book_of_life_page_link2_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, book_of_life_page_armleft_skinned),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 37, 0, 30, 28, 73),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, book_of_life_page_armleft_mesh),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, book_of_life_page_link3_skinned),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 37, 0, -10, 1, -13),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, book_of_life_page_link3_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, book_of_life_page_armright_skinned),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 35, 0, -37, 50, -109),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, book_of_life_page_armright_mesh),
								GEO_CLOSE_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, book_of_life_page_link4_skinned),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 35, 0, 9, 3, 14),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, book_of_life_page_link4_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, book_of_life_page_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
